driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.19.36

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-27
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[kernel_module_test]
