---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.19.36

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[kernel_module_test]
